# Generated by Django 3.2.5 on 2021-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='2021-12-01'),
        ),
    ]
