# Generated by Django 3.2.5 on 2021-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
