# Generated by Django 3.2.5 on 2021-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(db_index=True, default=1, unique=True),
        ),
    ]
