# Generated by Django 3.2.5 on 2021-12-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0006_auto_20211213_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
    ]
